name: Release feos-dft

on:
  push:
    tags: ["feos-dft-v*"]

jobs:
  release-crates-io:
    name: Release crates.io
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./feos-dft
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          path: './feos-dft'
